### ISSUE TITLE
Use key wrap for multiple recipients

### ISSUE THREAD

**Issue by laurencelundblade** [cose-wg/HPKE#11]
Seems like we will have to use key wrap like ECDH-ES + A128KW and friends do in RFC 9053 because Encap() and Decap() output a shared key. The don't public-key encrypt a CEK.

**Comment by hannestschofenig** [comment]
We discussed the use of Key Wrap for COSE-HPKE but there was no preference for it. Suggest to close this issue.

**Comment by laurencelundblade** [comment]
Agree to close. It's now clear that we can use HPKE directly to encrypt the CEK.
