### ISSUE TITLE
Support for more than HPKE base mode

### ISSUE THREAD

**Issue by laurencelundblade** [cose-wg/HPKE#14]
Since we're not defining how to integrate HPKE auth and other modes in this document is shouldn't be titled as if it were the full HPKE integration into COSE.

**Comment by laurencelundblade** [comment]
I would prefer it in the title, but if not in the title at least be clear that auth mode is not supported in the text and maybe that it should be supported in future work.

To go a bit further, I'm surprised auth mode is not of more interest. While I understand why it's not good for SUIT, it seems like it will:
 - is a solution to the sign-then-encrypt vs encrypt-then-sign issue 
 - be smaller on the wire
 - smaller code size

(Neither sign-then-encrypt vs encrypt-then-sign issue are fool-proof against all attacks in all use cases. It's not a problem for most use cases, but it's also nice to have fool-proof solutions).

**Comment by hannestschofenig** [comment]
Maybe we can leave it as an open issuer for now and discuss it at the meeting
