### ISSUE TITLE
Use of HPKE for COSE_Mac

### ISSUE THREAD

**Issue by hannestschofenig** [cose-wg/HPKE#24]
Daisuke wrote:

> COSE-HPKE can be applied to not only COSE_Encrypt but also COSE_Mac for the two layer structure. I think it would be better to include an explanation about COSE_Mac ( and provide an example for COSE_Mac).

**Comment by dajiaji** [comment]
I believe there should be no room for debate that COSE-HPKE can be used for 2-layer COSE_Mac as well, as long as it can be used for encrypting the CEK.

If you don't mind, shall I submit a pull request on this matter, including usage examples?

**Comment by hannestschofenig** [comment]
We in general need more examples in the draft and having examples for COSE_Mac would be good.

I will close the issue nevertheless because I have addressed the original issue
