### ISSUE TITLE
Replace the current examples with ciphersuite-based examples.

### ISSUE THREAD

**Issue by dajiaji** [cose-wg/HPKE#28]
Following the consensus call result, we have to replace the current examples with the ciphersuite-based examples.

For this,  it might be a good idea to select just one uncontroversial ciphersuite (e.g., HPKE-v1-Base-P256-SHA256-AES128GCM) in advance and update the examples using the ciphersuite.

**Comment by selfissued** [comment]
Having an uncontroversial ciphersuite would be good. ;-)
