### ISSUE TITLE
Remove version from ciphersuite

### ISSUE THREAD

**Issue by hannestschofenig** [cose-wg/HPKE#34]
I am proposing to remove the version indication from the ciphersuite. I don't recall anymore why we added it but it appears to be unnecessary.

**Comment by ilaril** [comment]
Agreed on removing the version. I think the reason why it was included was to prepare for HPKEv2, but I don't think that is a good reason.

I think it should be specified in the document that the mechanism is limited to HPKE version 1. I do not think it is a good idea to try to speculate what HPKE version 2 (if there ever is one) will be like. Such guesses can easily go very wrong; HPKEv2 in COSE should only be specified after HPKEv2 has been specified.

**Comment by dajiaji** [comment]
In fact, I was previously told by martin thompson that I should not worry about HPKE version information. Please see below.

https://github.com/ietf-wg-ohai/oblivious-http/issues/279

I think it is OK to remove it.
